
export const birdsData = [
  {
    name: "Grey Catbird",
    sciName: "Dumetella carolinensis",
    description: "Sleek, dark gray bird of North and Central America.",
    region: "North and Central America",
  },
  {
    name: "Northern Cardinal",
    sciName: "Cardinalis cardinalis",
    description: "Bright red bird with a distinctive crest.",
    region: "Eastern North America",
  },
  {
    name: "Blue Jay",
    sciName: "Cyanocitta cristata",
    description: "Bright blue, black, and white plumage; known for loud calls.",
    region: "Eastern and Central North America",
  },
  {
    name: "American Robin",
    sciName: "Turdus migratorius",
    description: "Common thrush known for its reddish-orange breast.",
    region: "North America",
  },
  {
    name: "Ruby-throated Hummingbird",
    sciName: "Archilochus colubris",
    description: "Small hummingbird; male has a brilliant ruby throat.",
    region: "Eastern North America",
  },
  {
    name: "Great Horned Owl",
    sciName: "Bubo virginianus",
    description: "Large, powerful owl with prominent ear tufts.",
    region: "The Americas",
  },
  {
    name: "Bald Eagle",
    sciName: "Haliaeetus leucocephalus",
    description: "North American bird of prey with a white head and dark body.",
    region: "North America",
  },
  {
    name: "House Sparrow",
    sciName: "Passer domesticus",
    description: "Small, widespread bird originally from the Middle East.",
    region: "Globally (introduced)",
  },
  {
    name: "Black-capped Chickadee",
    sciName: "Poecile atricapillus",
    description: "Small bird with a black cap and bib; highly vocal.",
    region: "North America",
  },
  {
    name: "European Starling",
    sciName: "Sturnus vulgaris",
    description: "Iridescent bird known for superb mimicry and large flocks.",
    region: "Europe, Asia, North America (introduced)",
  },
  {
    name: "Mallard",
    sciName: "Anas platyrhynchos",
    description: "Common dabbling duck found in temperate regions worldwide.",
    region: "Globally",
  },
  {
    name: "Osprey",
    sciName: "Pandion haliaetus",
    description: "Large raptor and specialized fish-eater with global distribution.",
    region: "Globally (near coasts and fresh water)",
  },
  {
    name: "Downy Woodpecker",
    sciName: "Dryobates pubescens",
    description: "The smallest North American woodpecker.",
    region: "North America",
  },
  {
    name: "Belted Kingfisher",
    sciName: "Megaceryle alcyon",
    description: "Large-headed bird with a shaggy crest; dives for fish.",
    region: "North America",
  },
  {
    name: "Red-tailed Hawk",
    sciName: "Buteo jamaicensis",
    description: "Large hawk easily identified by its broad, red tail.",
    region: "North America",
  },
  {
    name: "Barn Swallow",
    sciName: "Hirundo rustica",
    description: "Widespread swallow with a long, deeply forked tail.",
    region: "Globally",
  },
  {
    name: "American Goldfinch",
    sciName: "Spinus tristis",
    description: "Small finch; male is brilliant yellow in summer.",
    region: "North America",
  },
  {
    name: "Mourning Dove",
    sciName: "Zenaida macroura",
    description: "Common, widespread dove known for its gentle cooing call.",
    region: "North America",
  },
  {
    name: "Anna's Hummingbird",
    sciName: "Calypte anna",
    description: "Medium-sized hummingbird of the Western coast.",
    region: "Western North America",
  },
  {
    name: "Common Raven",
    sciName: "Corvus corax",
    description: "Large, all-black, highly intelligent passerine bird.",
    region: "Northern Hemisphere",
  },
  {
    name: "American Crow",
    sciName: "Corvus brachyrhynchos",
    description: "Large, intelligent, all-black bird with a familiar 'caw-caw' call.",
    region: "North America",
  },
  {
    name: "Black Vulture",
    sciName: "Coragyps atratus",
    description: "Large soaring bird with all-black plumage and a bare gray head.",
    region: "The Americas (South/East North America)",
  },
  {
    name: "Snowy Egret",
    sciName: "Egretta thula",
    description: "Elegant medium-sized white heron with black legs and brilliant yellow feet.",
    region: "The Americas (coastal wetlands)",
  },
  {
    name: "California Quail",
    sciName: "Callipepla californica",
    description: "Ground-dwelling bird known for its forward-curving head plume, or 'topknot'.",
    region: "Western North America",
  },
  {
    name: "Common Loon",
    sciName: "Gavia immer",
    description: "Iconic waterbird known for its striking breeding plumage and haunting calls.",
    region: "Northern Hemisphere (lakes and coasts)",
  },
]